exclude: [README.md]

encoding: utf-8
timezone: America/Los_Angeles

url: http://media.govalley.org
cdn: https://d2qybxhkdu1nl.cloudfront.net
permalink: /:year/:month/:day/:title.html


defaults:
    -
        scope:
            path: "podcast"
            type: "posts"
        values:
            layout: "podcast"


prose:
    media: "images"
